server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
spring:
  application:
    name: cart-service
  redis:
    host: 10.211.55.3
leyou:
  jwt:
    pubKeyPath: /Users/wentimei/Documents/Tools/Rsa/rsa.pub
    cookieName: LY-TOKEN
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

