server:
  port: 8083
spring:
  application:
    name: service-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 10.211.55.3:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    virtual-host: /leyou
    host: 10.211.55.3
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15