server:
  port: 8081
spring:
  application:
    name: leyou-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?characterEncoding=UTF-8
    username: root
    password: 123
  rabbitmq:
    host: 10.211.55.3
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEYOU-ITEM-EXCHANGE
    publisher-confirms: true
mybatis:
  type-aliases-package: com.leyou.item.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15